<?php
/*   __________________________________________________
    |  Obfuscated by YAK Pro - Php Obfuscator  2.0.3   |
    |              on 2020-11-16 14:57:02              |
    |    GitHub: https://github.com/pk-fr/yakpro-po    |
    |__________________________________________________|
*/
namespace Plugin\AmazonPay\Controller\Admin;use Eccube\Controller\AbstractController;use Plugin\AmazonPay\Form\Type\Admin\ConfigType;use Plugin\AmazonPay\Repository\ConfigRepository;use Symfony\Component\Form\FormError;use Symfony\Component\Routing\Annotation\Route;use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;use Symfony\Component\HttpFoundation\Request;use Symfony\Component\Validator\Constraints as Assert;use Symfony\Component\Validator\Validator\ValidatorInterface;class ConfigController extends AbstractController{protected $validator;protected $configRepository;public function __construct(ValidatorInterface $validator, ConfigRepository $configRepository){$this->validator = $validator;$this->configRepository = $configRepository;}    /**
     * @Route("/%eccube_admin_route%/amazon_pay/config", name="amazon_pay_admin_config")
     * @Template("@AmazonPay/admin/config.twig")
     */
public function index(Request $request){goto s8bpk;JRqcw:$this->entityManager->flush($Config);goto uh62j;F0C3V:$prod_key = $Config->getProdKey();goto wInjY;ew24u:xrD9_:goto G5gIu;aRn1N:if (!$form->isValid()) {goto CBozE;}goto DULHm;wInjY:$errors = $this->validator->validate($prod_key, [new Assert\NotBlank()]);goto ECw7c;EK7v3:return $this->redirectToRoute('amazon_pay_admin_config');goto ngaBl;Q2z5F:foreach ($errors as $error) {$messages[] = $error->getMessage();ZBsQH:}goto SsiRq;iT1DY:$form['prod_key']->addError(new FormError($messages[0]));goto mX5Ao;GBBNw:ts7Bu:goto hxNTH;fQDSE:$form = $this->createForm(ConfigType::class, $Config);goto p3HC1;DULHm:$this->entityManager->persist($Config);goto JRqcw;B3RY2:return ['form' => $form->createView(), 'testAccount' => $testAccount];goto aM3f5;qwLVo:if (!($Config->getEnv() == $this->eccubeConfig['amazon_pay']['env']['prod'])) {goto kBtJE;}goto F0C3V;gPHcB:if (!($form->isSubmitted() && $form->isValid())) {goto ts7Bu;}goto OoEQp;OoEQp:$Config = $form->getData();goto qwLVo;SsiRq:VP19e:goto iT1DY;s8bpk:$Config = $this->configRepository->get(true);goto fQDSE;ECw7c:if ($errors->count() != 0) {goto lm_sC;}goto Yd1dV;sPkwZ:kBtJE:goto aRn1N;ngaBl:CBozE:goto GBBNw;mX5Ao:HxXjB:goto sPkwZ;uh62j:$this->addSuccess('amazon_pay.admin.save.success', 'admin');goto EK7v3;WN8Fk:lm_sC:goto Q2z5F;G5gIu:goto HxXjB;goto WN8Fk;NAcqJ:$form['prod_key']->addError(new FormError('本番環境切り替えキーは有効なキーではありません。'));goto ew24u;hxNTH:$testAccount = $this->eccubeConfig['amazon_pay']['test_account'];goto B3RY2;Yd1dV:if (password_verify($prod_key, '$2y$10$R1Znq0V4FR4njvta3YMYEeNMm./pVeRHJUqw8JkpCyJW9FgfRzdSm')) {goto xrD9_;}goto NAcqJ;p3HC1:$form->handleRequest($request);goto gPHcB;aM3f5:}}