<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXqxvrav\EccubeProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXqxvrav/EccubeProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXqxvrav.legacy');

    return;
}

if (!\class_exists(EccubeProdProjectContainer::class, false)) {
    \class_alias(\ContainerXqxvrav\EccubeProdProjectContainer::class, EccubeProdProjectContainer::class, false);
}

return new \ContainerXqxvrav\EccubeProdProjectContainer([
    'container.build_hash' => 'Xqxvrav',
    'container.build_id' => '15bfaa12',
    'container.build_time' => 1606302357,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXqxvrav');
