<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Repository\BlockPositionRepository' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Repository/BlockPositionRepository.php';

return $this->services['Eccube\\Repository\\BlockPositionRepository'] = new \Eccube\Repository\BlockPositionRepository(${($_ = isset($this->services['Eccube\\Repository\\BlockRepository']) ? $this->services['Eccube\\Repository\\BlockRepository'] : $this->load('getBlockRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
