<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\EventListener\ForwardOnlyListener' shared service.

include_once $this->targetDirs[3].'/src/Eccube/EventListener/ForwardOnlyListener.php';

return $this->services['Eccube\\EventListener\\ForwardOnlyListener'] = new \Eccube\EventListener\ForwardOnlyListener();
