<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\EventListener\SecurityListener' shared service.

include_once $this->targetDirs[3].'/src/Eccube/EventListener/SecurityListener.php';

return $this->services['Eccube\\EventListener\\SecurityListener'] = new \Eccube\EventListener\SecurityListener();
