<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\EventListener\TransactionListener' shared service.

include_once $this->targetDirs[3].'/src/Eccube/EventListener/TransactionListener.php';

return $this->services['Eccube\\EventListener\\TransactionListener'] = new \Eccube\EventListener\TransactionListener();
