<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\EventListener\TwigInitializeListener' shared service.

include_once $this->targetDirs[3].'/src/Eccube/EventListener/TwigInitializeListener.php';

return $this->services['Eccube\\EventListener\\TwigInitializeListener'] = new \Eccube\EventListener\TwigInitializeListener();
