<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'monolog.handler.amazon_pay' shared service.

return $this->services['monolog.handler.amazon_pay'] = new \Monolog\Handler\FingersCrossedHandler(${($_ = isset($this->services['monolog.handler.amazon_pay_rotating_file']) ? $this->services['monolog.handler.amazon_pay_rotating_file'] : $this->load('getMonolog_Handler_AmazonPayRotatingFileService.php')) && false ?: '_'}, 400, 0, true, true, 200);
