<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\AmazonPay\Repository\PaymentStatusRepository' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/AmazonPay/Repository/PaymentStatusRepository.php';

return $this->services['Plugin\\AmazonPay\\Repository\\PaymentStatusRepository'] = new \Plugin\AmazonPay\Repository\PaymentStatusRepository(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
