<?php

namespace Proxies\__CG__\Plugin\AmazonPay\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AmazonTrading extends \Plugin\AmazonPay\Entity\AmazonTrading implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Plugin\\AmazonPay\\Entity\\AmazonTrading' . "\0" . 'id', '' . "\0" . 'Plugin\\AmazonPay\\Entity\\AmazonTrading' . "\0" . 'Order', '' . "\0" . 'Plugin\\AmazonPay\\Entity\\AmazonTrading' . "\0" . 'trading_code', '' . "\0" . 'Plugin\\AmazonPay\\Entity\\AmazonTrading' . "\0" . 'authori_amount', '' . "\0" . 'Plugin\\AmazonPay\\Entity\\AmazonTrading' . "\0" . 'capture_amount', '' . "\0" . 'Plugin\\AmazonPay\\Entity\\AmazonTrading' . "\0" . 'refund_count'];
        }

        return ['__isInitialized__', '' . "\0" . 'Plugin\\AmazonPay\\Entity\\AmazonTrading' . "\0" . 'id', '' . "\0" . 'Plugin\\AmazonPay\\Entity\\AmazonTrading' . "\0" . 'Order', '' . "\0" . 'Plugin\\AmazonPay\\Entity\\AmazonTrading' . "\0" . 'trading_code', '' . "\0" . 'Plugin\\AmazonPay\\Entity\\AmazonTrading' . "\0" . 'authori_amount', '' . "\0" . 'Plugin\\AmazonPay\\Entity\\AmazonTrading' . "\0" . 'capture_amount', '' . "\0" . 'Plugin\\AmazonPay\\Entity\\AmazonTrading' . "\0" . 'refund_count'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AmazonTrading $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrder(\Eccube\Entity\Order $Order)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrder', [$Order]);

        return parent::setOrder($Order);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrder', []);

        return parent::getOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setTradingCode($tradingCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTradingCode', [$tradingCode]);

        return parent::setTradingCode($tradingCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getTradingCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTradingCode', []);

        return parent::getTradingCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthoriAmount($authoriAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthoriAmount', [$authoriAmount]);

        return parent::setAuthoriAmount($authoriAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthoriAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthoriAmount', []);

        return parent::getAuthoriAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaptureAmount($captureAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaptureAmount', [$captureAmount]);

        return parent::setCaptureAmount($captureAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaptureAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaptureAmount', []);

        return parent::getCaptureAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefundCount($refundCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefundCount', [$refundCount]);

        return parent::setRefundCount($refundCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefundCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefundCount', []);

        return parent::getRefundCount();
    }

}
